### ISSUE TITLE
add dinosaur icons

### ISSUE THREAD

**Issue by vsoch** [openbases/openbases-icons#4]
:heart: https://www.flaticon.com/packs/dinosaur-set

**Comment by vsoch** [comment]
For this contribution, you just need to download the icons from the set, create a folder for them akin to other sets,and open the PR! It's a very good and easy hacktoberfest contribution!

**Comment by nautik1** [comment]
I'll do it!

**Comment by nautik1** [comment]
Wait, actually isn't there a license issue here?
https://file000.flaticon.com/downloads/license/license.pdf
```
What you CAN NOT DO: 
Distribute Flaticon Contents unless it has been expressly authorized by Flaticon
Include Flaticon Contents in an online or offline database or file
Offering Flaticon Contents designs (or modified Flaticon Contents versions) for download
```

**Comment by vsoch** [comment]
I think I’ve seen them ok for use with free oil - see the README in the folders! I cite that there as well as on the preview site.

**Comment by vsoch** [comment]
heyo I just submit a support/help request to freepik - let's hold off here until I can get an answer in case this isn't okay.  It's amazing that it might not be okay to share something so fun and cute (and give credit for the author) in an effort to make science fun! I hope they are able to suggest a good alternative if we are doing it wrong. Thanks for the heads up!

**Comment by vsoch** [comment]
hey @nipaDev ! You were right, and I've removed those icons. If you want to do a Hacktoberfest contribution, you can add something under a public domain license (e.g., I found these awesome tuxlets icons for that!) http://www.iconarchive.com/show/tuxlets-icons-by-mathijssen.html#iconlist
